# Generated by Django 2.1.12 on 2020-06-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursebranch',
            name='publication_status',
        ),
    ]
