# Generated by Django 2.1.12 on 2020-06-27 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_coursebranch_publication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='taken_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseBranch'),
        ),
    ]
