# Generated by Django 2.1.12 on 2020-06-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200627_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('passive', 'passive'), ('active', 'active')], max_length=100),
        ),
    ]
