# Generated by Django 2.1.12 on 2020-06-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20200630_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('passive', 'passive'), ('active', 'active')], default='passive', max_length=100),
        ),
    ]
