# Generated by Django 2.1.12 on 2020-07-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20200630_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='applicant_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='taken_course',
        ),
        migrations.DeleteModel(
            name='TestPerson',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
